const commandCode = {
  101: "Setup Show Text",
  102: "Show Choices",
  103: "Input Number",
  104: "Select Item",
  108: "Comment",
  111: "Conditional Branch",
  117: "Common Event",
  122: "Control Variables",
  123: "Control Self Switch",
  126: "Change Items",
  128: "Change Armor",
  129: "Change Party Member",
  201: "Transfer Player",
  231: "Show Picture",
  235: "Erase Picture",
  250: "Play SE",
  355: "Eval Script(Entry)",
  401: "Text Parameter",
  402: "When [**]",
  403: "When Cancel",
  408: "Comment",
  411: "Else",
  601: "If Win",
  602: "If Escape",
  603: "If Lose",
  655: "Eval Script",
} as Record<number, string>;
const commandParameter = {
  111: ["Type", "ID", "Value/Key", "Else"],
  117: ["Common Event ID"],
  123: ["SwitchCh", "On(0)/Off(1)"],
  126: ["Item ID", "Pos(0)/Neg(1)", "Immediate(0)/Variable(1)", "Value/Key"],
  129: ["Actor ID", "Add(0)/Remove(1)"],
  201: [
    ["Direct", "X", "Y", "Direction", "Fade Type"],
    ["Variable", "*X", "*Y", "Direction", "Fade Type"],
  ],
  250: ["SE"],
} as Record<number, string[] | string[][]>;
